# .github/workflows/publish-to-pypi-time_master.yml

name: Publish time_master to PyPI

on:
  push:
    tags:
      - 'time_master/v*'

jobs:
  build-and-publish:
    name: Build and publish time_master to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: python -m pip install --upgrade build

      - name: Build the package
        working-directory: ./time_master
        run: python -m build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: time_master/dist/*

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: time_master/dist/